recovery.c: Drop unused constant
Fixes error:
app/aboot/recovery.c:55:18: error: 'MISC_PAGES' defined but not used [-Werror=unused-const-variable=]
   55 | static const int MISC_PAGES = 3;   // number of pages to save

Signed-off-by: Petr Vorel <petr.vorel@gmail.com>